package metadark.mods.SuperSlopes.Corners;

import cpw.mods.fml.client.registry.RenderingRegistry;
import net.minecraft.src.ModLoader;

public class ClientInit extends CommonInit
{
    public void registerBlockModel()
    {
        Corners.CornersRenderID = RenderingRegistry.getNextAvailableRenderId();
        RenderingRegistry.registerBlockHandler(new RenderCorners());
    }

    public void addLocalizations()
    {
        ModLoader.addLocalization("KaevWoodSlopesQuadriCornerDown.name", "Wood Pyramid Corner");
        ModLoader.addLocalization("KaevWoodSlopesQuadriCornerUp.name", "Wood Pyramid Corner Inv");
        ModLoader.addLocalization("KaevWoodSlopesTriCornerDown.name", "Wood Corner Slope");
        ModLoader.addLocalization("KaevWoodSlopesTriCornerUp.name", "Wood Corner Slope Inv");
        ModLoader.addLocalization("KaevCobblestoneSlopesQuadriCornerDown.name", "Cobblestone Pyramid Corner");
        ModLoader.addLocalization("KaevCobblestoneSlopesQuadriCornerUp.name", "Cobblestone Pyramid Corner Inv");
        ModLoader.addLocalization("KaevCobblestoneSlopesTriCornerDown.name", "Cobblestone Corner Slope");
        ModLoader.addLocalization("KaevCobblestoneSlopesTriCornerUp.name", "Cobblestone Corner Slope Inv");
        ModLoader.addLocalization("KaevGlassSlopesQuadriCornerDown.name", "Glass Pyramid Corner");
        ModLoader.addLocalization("KaevGlassSlopesQuadriCornerUp.name", "Glass Pyramid Corner Inv");
        ModLoader.addLocalization("KaevGlassSlopesTriCornerDown.name", "Glass Corner Slope");
        ModLoader.addLocalization("KaevGlassSlopesTriCornerUp.name", "Glass Corner Slope Inv");
        ModLoader.addLocalization("KaevSandstoneSlopesQuadriCornerDown.name", "Sandstone Pyramid Corner");
        ModLoader.addLocalization("KaevSandstoneSlopesQuadriCornerUp.name", "Sandstone Pyramid Corner Inv");
        ModLoader.addLocalization("KaevSandstoneSlopesTriCornerDown.name", "Sandstone Corner Slope");
        ModLoader.addLocalization("KaevSandstoneSlopesTriCornerUp.name", "Sandstone Corner Slope Inv");
        ModLoader.addLocalization("KaevDirtSlopesQuadriCornerDown.name", "Dirt Pyramid Corner");
        ModLoader.addLocalization("KaevDirtSlopesQuadriCornerUp.name", "Dirt Pyramid Corner Inv");
        ModLoader.addLocalization("KaevDirtSlopesTriCornerDown.name", "Dirt Corner Slope");
        ModLoader.addLocalization("KaevDirtSlopesTriCornerUp.name", "Dirt Corner Slope Inv");
        ModLoader.addLocalization("KaevStoneSlopesQuadriCornerDown.name", "Stone Pyramid Corner");
        ModLoader.addLocalization("KaevStoneSlopesQuadriCornerUp.name", "Stone Pyramid Corner Inv");
        ModLoader.addLocalization("KaevStoneSlopesTriCornerDown.name", "Stone Corner Slope");
        ModLoader.addLocalization("KaevStoneSlopesTriCornerUp.name", "Stone Corner Slope Inv");
        ModLoader.addLocalization("KaevStoneBrickSlopesQuadriCornerDown.name", "Stone Brick Pyramid Corner");
        ModLoader.addLocalization("KaevStoneBrickSlopesQuadriCornerUp.name", "Stone Brick Pyramid Corner Inv");
        ModLoader.addLocalization("KaevStoneBrickSlopesTriCornerDown.name", "Stone Brick Corner Slope");
        ModLoader.addLocalization("KaevStoneBrickSlopesTriCornerUp.name", "Stone Brick Corner Slope Inv");
        ModLoader.addLocalization("KaevSandSlopesQuadriCornerDown.name", "Sand Pyramid Corner");
        ModLoader.addLocalization("KaevSandSlopesQuadriCornerUp.name", "Sand Pyramid Corner Inv");
        ModLoader.addLocalization("KaevSandSlopesTriCornerDown.name", "Sand Corner Slope");
        ModLoader.addLocalization("KaevSandSlopesTriCornerUp.name", "Sand Corner Slope Inv");
        ModLoader.addLocalization("KaevSnowSlopesQuadriCornerDown.name", "Snow Pyramid Corner");
        ModLoader.addLocalization("KaevSnowSlopesQuadriCornerUp.name", "Snow Pyramid Corner Inv");
        ModLoader.addLocalization("KaevSnowSlopesTriCornerDown.name", "Snow Corner Slope");
        ModLoader.addLocalization("KaevSnowSlopesTriCornerUp.name", "Snow Corner Slope Inv");
        ModLoader.addLocalization("KaevGrassSlopesQuadriCornerDown.name", "Grass Pyramid Corner");
        ModLoader.addLocalization("KaevGrassSlopesQuadriCornerUp.name", "Grass Pyramid Corner Inv");
        ModLoader.addLocalization("KaevGrassSlopesTriCornerDown.name", "Grass Corner Slope");
        ModLoader.addLocalization("KaevGrassSlopesTriCornerUp.name", "Grass Corner Slope Inv");
        ModLoader.addLocalization("KaevBricksSlopesQuadriCornerDown.name", "Brick Pyramid Corner");
        ModLoader.addLocalization("KaevBricksSlopesQuadriCornerUp.name", "Brick Pyramid Corner Inv");
        ModLoader.addLocalization("KaevBricksSlopesTriCornerDown.name", "Brick Corner Slope");
        ModLoader.addLocalization("KaevBricksSlopesTriCornerUp.name", "Brick Corner Slope Inv");
        ModLoader.addLocalization("KaevGravelSlopesQuadriCornerDown.name", "Gravel Pyramid Corner");
        ModLoader.addLocalization("KaevGravelSlopesQuadriCornerUp.name", "Gravel Pyramid Corner Inv");
        ModLoader.addLocalization("KaevGravelSlopesTriCornerDown.name", "Gravel Corner Slope");
        ModLoader.addLocalization("KaevGravelSlopesTriCornerUp.name", "Gravel Corner Slope Inv");
        ModLoader.addLocalization("KaevGoldSlopesQuadriCornerDown.name", "Gold Pyramid Corner");
        ModLoader.addLocalization("KaevGoldSlopesQuadriCornerUp.name", "Gold Pyramid Corner Inv");
        ModLoader.addLocalization("KaevGoldSlopesTriCornerDown.name", "Gold Corner Slope");
        ModLoader.addLocalization("KaevGoldSlopesTriCornerUp.name", "Gold Corner Slope Inv");
        ModLoader.addLocalization("KaevSteelSlopesQuadriCornerDown.name", "Iron Pyramid Corner");
        ModLoader.addLocalization("KaevSteelSlopesQuadriCornerUp.name", "Iron Pyramid Corner Inv");
        ModLoader.addLocalization("KaevSteelSlopesTriCornerDown.name", "Iron Corner Slope");
        ModLoader.addLocalization("KaevSteelSlopesTriCornerUp.name", "Iron Corner Slope Inv");
        ModLoader.addLocalization("KaevObsidianSlopesQuadriCornerDown.name", "Obsidian Pyramid Corner");
        ModLoader.addLocalization("KaevObsidianSlopesQuadriCornerUp.name", "Obsidian Pyramid Corner Inv");
        ModLoader.addLocalization("KaevObsidianSlopesTriCornerDown.name", "Obsidian Corner Slope");
        ModLoader.addLocalization("KaevObsidianSlopesTriCornerUp.name", "Obsidian Corner Slope Inv");
        ModLoader.addLocalization("KaevNetherBrickSlopesQuadriCornerDown.name", "Nether Brick Pyramid Corner");
        ModLoader.addLocalization("KaevNetherBrickSlopesQuadriCornerUp.name", "Nether Brick Pyramid Corner Inv");
        ModLoader.addLocalization("KaevNetherBrickSlopesTriCornerDown.name", "Nether Brick Corner Slope");
        ModLoader.addLocalization("KaevNetherBrickSlopesTriCornerUp.name", "Nether Brick Corner Slope Inv");
        ModLoader.addLocalization("KaevDiamondSlopesQuadriCornerDown.name", "Diamond Pyramid Corner");
        ModLoader.addLocalization("KaevDiamondSlopesQuadriCornerUp.name", "Diamond Pyramid Corner Inv");
        ModLoader.addLocalization("KaevDiamondSlopesTriCornerDown.name", "Diamond Corner Slope");
        ModLoader.addLocalization("KaevDiamondSlopesTriCornerUp.name", "Diamond Corner Slope Inv");
        ModLoader.addLocalization("KaevWhiteWoolSlopesQuadriCornerDown.name", "Wool Pyramid Corner");
        ModLoader.addLocalization("KaevWhiteWoolSlopesQuadriCornerUp.name", "Wool Pyramid Corner Inv");
        ModLoader.addLocalization("KaevWhiteWoolSlopesTriCornerDown.name", "Wool Corner Slope");
        ModLoader.addLocalization("KaevWhiteWoolSlopesTriCornerUp.name", "Wool Corner Slope Inv");
        ModLoader.addLocalization("KaevBlackWoolSlopesQuadriCornerDown.name", "Black Pyramid Corner");
        ModLoader.addLocalization("KaevBlackWoolSlopesQuadriCornerUp.name", "Black Pyramid Corner Inv");
        ModLoader.addLocalization("KaevBlackWoolSlopesTriCornerDown.name", "Black Corner Slope");
        ModLoader.addLocalization("KaevBlackWoolSlopesTriCornerUp.name", "Black Corner Slope Inv");
        ModLoader.addLocalization("KaevRedWoolSlopesQuadriCornerDown.name", "Red Pyramid Corner");
        ModLoader.addLocalization("KaevRedWoolSlopesQuadriCornerUp.name", "Red Pyramid Corner Inv");
        ModLoader.addLocalization("KaevRedWoolSlopesTriCornerDown.name", "Red Corner Slope");
        ModLoader.addLocalization("KaevRedWoolSlopesTriCornerUp.name", "Red Corner Slope Inv");
        ModLoader.addLocalization("KaevGreenWoolSlopesQuadriCornerDown.name", "Green Pyramid Corner");
        ModLoader.addLocalization("KaevGreenWoolSlopesQuadriCornerUp.name", "Green Pyramid Corner Inv");
        ModLoader.addLocalization("KaevGreenWoolSlopesTriCornerDown.name", "Green Corner Slope");
        ModLoader.addLocalization("KaevGreenWoolSlopesTriCornerUp.name", "Green Corner Slope Inv");
        ModLoader.addLocalization("KaevBrownWoolSlopesQuadriCornerDown.name", "Brown Pyramid Corner");
        ModLoader.addLocalization("KaevBrownWoolSlopesQuadriCornerUp.name", "Brown Pyramid Corner Inv");
        ModLoader.addLocalization("KaevBrownWoolSlopesTriCornerDown.name", "Brown Corner Slope");
        ModLoader.addLocalization("KaevBrownWoolSlopesTriCornerUp.name", "Brown Corner Slope Inv");
        ModLoader.addLocalization("KaevBlueWoolSlopesQuadriCornerDown.name", "Blue Pyramid Corner");
        ModLoader.addLocalization("KaevBlueWoolSlopesQuadriCornerUp.name", "Blue Pyramid Corner Inv");
        ModLoader.addLocalization("KaevBlueWoolSlopesTriCornerDown.name", "Blue Corner Slope");
        ModLoader.addLocalization("KaevBlueWoolSlopesTriCornerUp.name", "Blue Corner Slope Inv");
        ModLoader.addLocalization("KaevPurpleWoolSlopesQuadriCornerDown.name", "Purple Pyramid Corner");
        ModLoader.addLocalization("KaevPurpleWoolSlopesQuadriCornerUp.name", "Purple Pyramid Corner Inv");
        ModLoader.addLocalization("KaevPurpleWoolSlopesTriCornerDown.name", "Purple Corner Slope");
        ModLoader.addLocalization("KaevPurpleWoolSlopesTriCornerUp.name", "Purple Corner Slope Inv");
        ModLoader.addLocalization("KaevCyanWoolSlopesQuadriCornerDown.name", "Cyan Pyramid Corner");
        ModLoader.addLocalization("KaevCyanWoolSlopesQuadriCornerUp.name", "Cyan Pyramid Corner Inv");
        ModLoader.addLocalization("KaevCyanWoolSlopesTriCornerDown.name", "Cyan Corner Slope");
        ModLoader.addLocalization("KaevCyanWoolSlopesTriCornerUp.name", "Cyan Corner Slope Inv");
        ModLoader.addLocalization("KaevSilverWoolSlopesQuadriCornerDown.name", "Light Gray Pyramid Corner");
        ModLoader.addLocalization("KaevSilverWoolSlopesQuadriCornerUp.name", "Light Gray Pyramid Corner Inv");
        ModLoader.addLocalization("KaevSilverWoolSlopesTriCornerDown.name", "Light Gray Corner Slope");
        ModLoader.addLocalization("KaevSilverWoolSlopesTriCornerUp.name", "Light Gray Corner Slope Inv");
        ModLoader.addLocalization("KaevGrayWoolSlopesQuadriCornerDown.name", "Gray Pyramid Corner");
        ModLoader.addLocalization("KaevGrayWoolSlopesQuadriCornerUp.name", "Gray Pyramid Corner Inv");
        ModLoader.addLocalization("KaevGrayWoolSlopesTriCornerDown.name", "Gray Corner Slope");
        ModLoader.addLocalization("KaevGrayWoolSlopesTriCornerUp.name", "Gray Corner Slope Inv");
        ModLoader.addLocalization("KaevPinkWoolSlopesQuadriCornerDown.name", "Pink Pyramid Corner");
        ModLoader.addLocalization("KaevPinkWoolSlopesQuadriCornerUp.name", "Pink Pyramid Corner Inv");
        ModLoader.addLocalization("KaevPinkWoolSlopesTriCornerDown.name", "Pink Corner Slope");
        ModLoader.addLocalization("KaevPinkWoolSlopesTriCornerUp.name", "Pink Corner Slope Inv");
        ModLoader.addLocalization("KaevLimeWoolSlopesQuadriCornerDown.name", "Lime Pyramid Corner");
        ModLoader.addLocalization("KaevLimeWoolSlopesQuadriCornerUp.name", "Lime Pyramid Corner Inv");
        ModLoader.addLocalization("KaevLimeWoolSlopesTriCornerDown.name", "Lime Corner Slope");
        ModLoader.addLocalization("KaevLimeWoolSlopesTriCornerUp.name", "Lime Corner Slope Inv");
        ModLoader.addLocalization("KaevYellowWoolSlopesQuadriCornerDown.name", "Yellow Pyramid Corner");
        ModLoader.addLocalization("KaevYellowWoolSlopesQuadriCornerUp.name", "Yellow Pyramid Corner Inv");
        ModLoader.addLocalization("KaevYellowWoolSlopesTriCornerDown.name", "Yellow Corner Slope");
        ModLoader.addLocalization("KaevYellowWoolSlopesTriCornerUp.name", "Yellow Corner Slope Inv");
        ModLoader.addLocalization("KaevLightBlueWoolSlopesQuadriCornerDown.name", "Light Blue Pyramid Corner");
        ModLoader.addLocalization("KaevLightBlueWoolSlopesQuadriCornerUp.name", "Light Blue Pyramid Corner Inv");
        ModLoader.addLocalization("KaevLightBlueWoolSlopesTriCornerDown.name", "Light Blue Corner Slope");
        ModLoader.addLocalization("KaevLightBlueWoolSlopesTriCornerUp.name", "Light Blue Corner Slope Inv");
        ModLoader.addLocalization("KaevMagentaWoolSlopesQuadriCornerDown.name", "Magenta Pyramid Corner");
        ModLoader.addLocalization("KaevMagentaWoolSlopesQuadriCornerUp.name", "Magenta Pyramid Corner Inv");
        ModLoader.addLocalization("KaevMagentaWoolSlopesTriCornerDown.name", "Magenta Corner Slope");
        ModLoader.addLocalization("KaevMagentaWoolSlopesTriCornerUp.name", "Magenta Corner Slope Inv");
        ModLoader.addLocalization("KaevOrangeWoolSlopesQuadriCornerDown.name", "Orange Pyramid Corner");
        ModLoader.addLocalization("KaevOrangeWoolSlopesQuadriCornerUp.name", "Orange Pyramid Corner Inv");
        ModLoader.addLocalization("KaevOrangeWoolSlopesTriCornerDown.name", "Orange Corner Slope");
        ModLoader.addLocalization("KaevOrangeWoolSlopesTriCornerUp.name", "Orange Corner Slope Inv");
    }
}
