package metadark.mods.SuperSlopes.Slopes;

import cpw.mods.fml.client.registry.RenderingRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class ClientInit extends CommonInit
{
    public void registerBlockModel()
    {
        Slopes.SlopesRenderID = RenderingRegistry.getNextAvailableRenderId();
        RenderingRegistry.registerBlockHandler(new RenderSlopes());
    }

    public void addLocalizations()
    {
        LanguageRegistry.instance().addStringLocalization("KaevWoodSlopesStairsUp.name", "Wood Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevWoodSlopesSlopeDown.name", "Wood Slope");
        LanguageRegistry.instance().addStringLocalization("KaevWoodSlopesSlopeUp.name", "Wood Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevWoodSlopesSlopeSide.name", "Wood Corner");
        LanguageRegistry.instance().addStringLocalization("KaevCobblestoneSlopesStairsUp.name", "Cobblestone Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevCobblestoneSlopesSlopeDown.name", "Cobblestone Slope");
        LanguageRegistry.instance().addStringLocalization("KaevCobblestoneSlopesSlopeUp.name", "Cobblestone Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevCobblestoneSlopesSlopeSide.name", "Cobblestone Corner");
        LanguageRegistry.instance().addStringLocalization("KaevGlassSlopesStairsUp.name", "Glass Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGlassSlopesSlopeDown.name", "Glass Slope");
        LanguageRegistry.instance().addStringLocalization("KaevGlassSlopesSlopeUp.name", "Glass Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGlassSlopesSlopeSide.name", "Glass Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSandstoneSlopesStairsUp.name", "Sandstone Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSandstoneSlopesSlopeDown.name", "Sandstone Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSandstoneSlopesSlopeUp.name", "Sandstone Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSandstoneSlopesSlopeSide.name", "Sandstone Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSmoothSandstoneSlopesStairsUp.name", "Smooth Sandstone Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSmoothSandstoneSlopesSlopeDown.name", "Smooth Sandstone Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSmoothSandstoneSlopesSlopeUp.name", "Smooth Sandstone Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSmoothSandstoneSlopesSlopeSide.name", "Smooth Sandstone Corner");
        LanguageRegistry.instance().addStringLocalization("KaevChiseledSandstoneSlopesStairsUp.name", "Chiseled Sandstone Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevChiseledSandstoneSlopesSlopeDown.name", "Chiseled Sandstone Slope");
        LanguageRegistry.instance().addStringLocalization("KaevChiseledSandstoneSlopesSlopeUp.name", "Chiseled Sandstone Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevChiseledSandstoneSlopesSlopeSide.name", "Chiseled Sandstone Corner");
        LanguageRegistry.instance().addStringLocalization("KaevDirtSlopesStairsUp.name", "Dirt Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevDirtSlopesSlopeDown.name", "Dirt Slope");
        LanguageRegistry.instance().addStringLocalization("KaevDirtSlopesSlopeUp.name", "Dirt Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevDirtSlopesSlopeSide.name", "Dirt Corner");
        LanguageRegistry.instance().addStringLocalization("KaevStoneSlopesStairsUp.name", "Stone Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevStoneSlopesSlopeDown.name", "Stone Slope");
        LanguageRegistry.instance().addStringLocalization("KaevStoneSlopesSlopeUp.name", "Stone Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevStoneSlopesSlopeSide.name", "Stone Corner");
        LanguageRegistry.instance().addStringLocalization("KaevStoneBrickSlopesSlopeDown.name", "Stone Brick Slope");
        LanguageRegistry.instance().addStringLocalization("KaevStoneBrickSlopesSlopeUp.name", "Stone Brick Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevStoneBrickSlopesSlopeSide.name", "Stone Brick Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSandSlopesStairsUp.name", "Sand Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSandSlopesSlopeDown.name", "Sand Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSandSlopesSlopeUp.name", "Sand Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSandSlopesSlopeSide.name", "Sand Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSandSlopesStairsUp.name", "Sand Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSandSlopesSlopeDown.name", "Sand Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSandSlopesSlopeUp.name", "Sand Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSandSlopesSlopeSide.name", "Sand Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSnowSlopesStairsUp.name", "Snow Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSnowSlopesSlopeDown.name", "Snow Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSnowSlopesSlopeUp.name", "Snow Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSnowSlopesSlopeSide.name", "Snow Corner");
        LanguageRegistry.instance().addStringLocalization("KaevGrassSlopesStairsUp.name", "Grass Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGrassSlopesSlopeDown.name", "Grass Slope");
        LanguageRegistry.instance().addStringLocalization("KaevGrassSlopesSlopeUp.name", "Grass Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGrassSlopesSlopeSide.name", "Grass Corner");
        LanguageRegistry.instance().addStringLocalization("KaevBricksSlopesStairsUp.name", "Brick Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBricksSlopesSlopeDown.name", "Brick Slope");
        LanguageRegistry.instance().addStringLocalization("KaevBricksSlopesSlopeUp.name", "Brick Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBricksSlopesSlopeSide.name", "Brick Corner");
        LanguageRegistry.instance().addStringLocalization("KaevGravelSlopesStairsUp.name", "Gravel Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGravelSlopesSlopeDown.name", "Gravel Slope");
        LanguageRegistry.instance().addStringLocalization("KaevGravelSlopesSlopeUp.name", "Gravel Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGravelSlopesSlopeSide.name", "Gravel Corner");
        LanguageRegistry.instance().addStringLocalization("KaevGoldSlopesStairsUp.name", "Gold Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGoldSlopesSlopeDown.name", "Gold Slope");
        LanguageRegistry.instance().addStringLocalization("KaevGoldSlopesSlopeUp.name", "Gold Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGoldSlopesSlopeSide.name", "Gold Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSteelSlopesStairsUp.name", "Iron Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSteelSlopesSlopeDown.name", "Iron Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSteelSlopesSlopeUp.name", "Iron Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSteelSlopesSlopeSide.name", "Iron Corner");
        LanguageRegistry.instance().addStringLocalization("KaevObsidianSlopesStairsUp.name", "Obsidian Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevObsidianSlopesSlopeDown.name", "Obsidian Slope");
        LanguageRegistry.instance().addStringLocalization("KaevObsidianSlopesSlopeUp.name", "Obsidian Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevObsidianSlopesSlopeSide.name", "Obsidian Corner");
        LanguageRegistry.instance().addStringLocalization("KaevNetherBrickSlopesSlopeDown.name", "Nether Brick Slope");
        LanguageRegistry.instance().addStringLocalization("KaevNetherBrickSlopesSlopeUp.name", "Nether Brick Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevNetherBrickSlopesSlopeSide.name", "Nether Brick Corner");
        LanguageRegistry.instance().addStringLocalization("KaevDiamondSlopesStairsUp.name", "Diamond Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevDiamondSlopesSlopeDown.name", "Diamond Slope");
        LanguageRegistry.instance().addStringLocalization("KaevDiamondSlopesSlopeUp.name", "Diamond Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevDiamondSlopesSlopeSide.name", "Diamond Corner");
        LanguageRegistry.instance().addStringLocalization("KaevWhiteWoolSlopesStairsUp.name", "Wool Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevWhiteWoolSlopesSlopeDown.name", "Wool Slope");
        LanguageRegistry.instance().addStringLocalization("KaevWhiteWoolSlopesSlopeUp.name", "Wool Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevWhiteWoolSlopesSlopeSide.name", "Wool Corner");
        LanguageRegistry.instance().addStringLocalization("KaevBlackWoolSlopesStairsUp.name", "Black Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBlackWoolSlopesSlopeDown.name", "Black Slope");
        LanguageRegistry.instance().addStringLocalization("KaevBlackWoolSlopesSlopeUp.name", "Black Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBlackWoolSlopesSlopeSide.name", "Black Corner");
        LanguageRegistry.instance().addStringLocalization("KaevRedWoolSlopesStairsUp.name", "Red Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevRedWoolSlopesSlopeDown.name", "Red Slope");
        LanguageRegistry.instance().addStringLocalization("KaevRedWoolSlopesSlopeUp.name", "Red Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevRedWoolSlopesSlopeSide.name", "Red Corner");
        LanguageRegistry.instance().addStringLocalization("KaevGreenWoolSlopesStairsUp.name", "Green Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGreenWoolSlopesSlopeDown.name", "Green Slope");
        LanguageRegistry.instance().addStringLocalization("KaevGreenWoolSlopesSlopeUp.name", "Green Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGreenWoolSlopesSlopeSide.name", "Green Corner");
        LanguageRegistry.instance().addStringLocalization("KaevBrownWoolSlopesStairsUp.name", "Brown Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBrownWoolSlopesSlopeDown.name", "Brown Slope");
        LanguageRegistry.instance().addStringLocalization("KaevBrownWoolSlopesSlopeUp.name", "Brown Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBrownWoolSlopesSlopeSide.name", "Brown Corner");
        LanguageRegistry.instance().addStringLocalization("KaevBlueWoolSlopesStairsUp.name", "Blue Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBlueWoolSlopesSlopeDown.name", "Blue Slope");
        LanguageRegistry.instance().addStringLocalization("KaevBlueWoolSlopesSlopeUp.name", "Blue Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBlueWoolSlopesSlopeSide.name", "Blue Corner");
        LanguageRegistry.instance().addStringLocalization("KaevPurpleWoolSlopesStairsUp.name", "Purple Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevPurpleWoolSlopesSlopeDown.name", "Purple Slope");
        LanguageRegistry.instance().addStringLocalization("KaevPurpleWoolSlopesSlopeUp.name", "Purple Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevPurpleWoolSlopesSlopeSide.name", "Purple Corner");
        LanguageRegistry.instance().addStringLocalization("KaevCyanWoolSlopesStairsUp.name", "Cyan Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevCyanWoolSlopesSlopeDown.name", "Cyan Slope");
        LanguageRegistry.instance().addStringLocalization("KaevCyanWoolSlopesSlopeUp.name", "Cyan Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevCyanWoolSlopesSlopeSide.name", "Cyan Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSilverWoolSlopesStairsUp.name", "Light Gray Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSilverWoolSlopesSlopeDown.name", "Light Gray Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSilverWoolSlopesSlopeUp.name", "Light Gray Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSilverWoolSlopesSlopeSide.name", "Light Gray Corner");
        LanguageRegistry.instance().addStringLocalization("KaevGrayWoolSlopesStairsUp.name", "Gray Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGrayWoolSlopesSlopeDown.name", "Gray Slope");
        LanguageRegistry.instance().addStringLocalization("KaevGrayWoolSlopesSlopeUp.name", "Gray Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGrayWoolSlopesSlopeSide.name", "Gray Corner");
        LanguageRegistry.instance().addStringLocalization("KaevPinkWoolSlopesStairsUp.name", "Pink Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevPinkWoolSlopesSlopeDown.name", "Pink Slope");
        LanguageRegistry.instance().addStringLocalization("KaevPinkWoolSlopesSlopeUp.name", "Pink Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevPinkWoolSlopesSlopeSide.name", "Pink Corner");
        LanguageRegistry.instance().addStringLocalization("KaevLimeWoolSlopesStairsUp.name", "Lime Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevLimeWoolSlopesSlopeDown.name", "Lime Slope");
        LanguageRegistry.instance().addStringLocalization("KaevLimeWoolSlopesSlopeUp.name", "Lime Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevLimeWoolSlopesSlopeSide.name", "Lime Corner");
        LanguageRegistry.instance().addStringLocalization("KaevYellowWoolSlopesStairsUp.name", "Yellow Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevYellowWoolSlopesSlopeDown.name", "Yellow Slope");
        LanguageRegistry.instance().addStringLocalization("KaevYellowWoolSlopesSlopeUp.name", "Yellow Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevYellowWoolSlopesSlopeSide.name", "Yellow Corner");
        LanguageRegistry.instance().addStringLocalization("KaevLightBlueWoolSlopesStairsUp.name", "Light Blue Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevLightBlueWoolSlopesSlopeDown.name", "Light Blue Slope");
        LanguageRegistry.instance().addStringLocalization("KaevLightBlueWoolSlopesSlopeUp.name", "Light Blue Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevLightBlueWoolSlopesSlopeSide.name", "Light Blue Corner");
        LanguageRegistry.instance().addStringLocalization("KaevMagentaWoolSlopesStairsUp.name", "Magenta Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevMagentaWoolSlopesSlopeDown.name", "Magenta Slope");
        LanguageRegistry.instance().addStringLocalization("KaevMagentaWoolSlopesSlopeUp.name", "Magenta Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevMagentaWoolSlopesSlopeSide.name", "Magenta Corner");
        LanguageRegistry.instance().addStringLocalization("KaevOrangeWoolSlopesStairsUp.name", "Orange Stairs Inv");
        LanguageRegistry.instance().addStringLocalization("KaevOrangeWoolSlopesSlopeDown.name", "Orange Slope");
        LanguageRegistry.instance().addStringLocalization("KaevOrangeWoolSlopesSlopeUp.name", "Orange Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevOrangeWoolSlopesSlopeSide.name", "Orange Corner");
    }
}
