package metadark.mods.SuperSlopes.Corners;

import cpw.mods.fml.client.registry.RenderingRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class ClientInit extends CommonInit {
    public void registerBlockModel() {
        Corners.CornersRenderID = RenderingRegistry.getNextAvailableRenderId();
        RenderingRegistry.registerBlockHandler(new RenderCorners());
    }

    public void addLocalizations() {
        LanguageRegistry.instance().addStringLocalization("KaevWoodSlopesQuadriCornerDown.name", "Wood Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevWoodSlopesQuadriCornerUp.name", "Wood Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevWoodSlopesTriCornerDown.name", "Wood Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevWoodSlopesTriCornerUp.name", "Wood Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevCobblestoneSlopesQuadriCornerDown.name", "Cobblestone Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevCobblestoneSlopesQuadriCornerUp.name", "Cobblestone Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevCobblestoneSlopesTriCornerDown.name", "Cobblestone Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevCobblestoneSlopesTriCornerUp.name", "Cobblestone Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGlassSlopesQuadriCornerDown.name", "Glass Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevGlassSlopesQuadriCornerUp.name", "Glass Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGlassSlopesTriCornerDown.name", "Glass Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevGlassSlopesTriCornerUp.name", "Glass Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSandstoneSlopesQuadriCornerDown.name", "Sandstone Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSandstoneSlopesQuadriCornerUp.name", "Sandstone Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSandstoneSlopesTriCornerDown.name", "Sandstone Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSandstoneSlopesTriCornerUp.name", "Sandstone Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSmoothSandstoneSlopesQuadriCornerDown.name", "Smooth Sandstone Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSmoothSandstoneSlopesQuadriCornerUp.name", "Smooth Sandstone Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSmoothSandstoneSlopesTriCornerDown.name", "Smooth Sandstone Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSmoothSandstoneSlopesTriCornerUp.name", "Smooth Sandstone Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevChiseledSandstoneSlopesQuadriCornerDown.name", "Chiseled Sandstone Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevChiseledSandstoneSlopesQuadriCornerUp.name", "Chiseled Sandstone Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevChiseledSandstoneSlopesTriCornerDown.name", "Chiseled Sandstone Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevChiseledSandstoneSlopesTriCornerUp.name", "Chiseled Sandstone Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevDirtSlopesQuadriCornerDown.name", "Dirt Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevDirtSlopesQuadriCornerUp.name", "Dirt Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevDirtSlopesTriCornerDown.name", "Dirt Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevDirtSlopesTriCornerUp.name", "Dirt Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevStoneSlopesQuadriCornerDown.name", "Stone Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevStoneSlopesQuadriCornerUp.name", "Stone Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevStoneSlopesTriCornerDown.name", "Stone Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevStoneSlopesTriCornerUp.name", "Stone Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevStoneBrickSlopesQuadriCornerDown.name", "Stone Brick Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevStoneBrickSlopesQuadriCornerUp.name", "Stone Brick Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevStoneBrickSlopesTriCornerDown.name", "Stone Brick Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevStoneBrickSlopesTriCornerUp.name", "Stone Brick Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSandSlopesQuadriCornerDown.name", "Sand Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSandSlopesQuadriCornerUp.name", "Sand Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSandSlopesTriCornerDown.name", "Sand Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSandSlopesTriCornerUp.name", "Sand Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSnowSlopesQuadriCornerDown.name", "Snow Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSnowSlopesQuadriCornerUp.name", "Snow Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSnowSlopesTriCornerDown.name", "Snow Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSnowSlopesTriCornerUp.name", "Snow Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGrassSlopesQuadriCornerDown.name", "Grass Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevGrassSlopesQuadriCornerUp.name", "Grass Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGrassSlopesTriCornerDown.name", "Grass Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevGrassSlopesTriCornerUp.name", "Grass Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBricksSlopesQuadriCornerDown.name", "Brick Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevBricksSlopesQuadriCornerUp.name", "Brick Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBricksSlopesTriCornerDown.name", "Brick Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevBricksSlopesTriCornerUp.name", "Brick Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGravelSlopesQuadriCornerDown.name", "Gravel Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevGravelSlopesQuadriCornerUp.name", "Gravel Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGravelSlopesTriCornerDown.name", "Gravel Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevGravelSlopesTriCornerUp.name", "Gravel Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGoldSlopesQuadriCornerDown.name", "Gold Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevGoldSlopesQuadriCornerUp.name", "Gold Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGoldSlopesTriCornerDown.name", "Gold Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevGoldSlopesTriCornerUp.name", "Gold Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSteelSlopesQuadriCornerDown.name", "Iron Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSteelSlopesQuadriCornerUp.name", "Iron Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSteelSlopesTriCornerDown.name", "Iron Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSteelSlopesTriCornerUp.name", "Iron Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevObsidianSlopesQuadriCornerDown.name", "Obsidian Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevObsidianSlopesQuadriCornerUp.name", "Obsidian Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevObsidianSlopesTriCornerDown.name", "Obsidian Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevObsidianSlopesTriCornerUp.name", "Obsidian Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevNetherBrickSlopesQuadriCornerDown.name", "Nether Brick Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevNetherBrickSlopesQuadriCornerUp.name", "Nether Brick Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevNetherBrickSlopesTriCornerDown.name", "Nether Brick Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevNetherBrickSlopesTriCornerUp.name", "Nether Brick Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevDiamondSlopesQuadriCornerDown.name", "Diamond Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevDiamondSlopesQuadriCornerUp.name", "Diamond Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevDiamondSlopesTriCornerDown.name", "Diamond Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevDiamondSlopesTriCornerUp.name", "Diamond Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevWhiteWoolSlopesQuadriCornerDown.name", "Wool Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevWhiteWoolSlopesQuadriCornerUp.name", "Wool Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevWhiteWoolSlopesTriCornerDown.name", "Wool Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevWhiteWoolSlopesTriCornerUp.name", "Wool Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBlackWoolSlopesQuadriCornerDown.name", "Black Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevBlackWoolSlopesQuadriCornerUp.name", "Black Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBlackWoolSlopesTriCornerDown.name", "Black Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevBlackWoolSlopesTriCornerUp.name", "Black Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevRedWoolSlopesQuadriCornerDown.name", "Red Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevRedWoolSlopesQuadriCornerUp.name", "Red Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevRedWoolSlopesTriCornerDown.name", "Red Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevRedWoolSlopesTriCornerUp.name", "Red Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGreenWoolSlopesQuadriCornerDown.name", "Green Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevGreenWoolSlopesQuadriCornerUp.name", "Green Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGreenWoolSlopesTriCornerDown.name", "Green Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevGreenWoolSlopesTriCornerUp.name", "Green Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBrownWoolSlopesQuadriCornerDown.name", "Brown Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevBrownWoolSlopesQuadriCornerUp.name", "Brown Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBrownWoolSlopesTriCornerDown.name", "Brown Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevBrownWoolSlopesTriCornerUp.name", "Brown Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBlueWoolSlopesQuadriCornerDown.name", "Blue Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevBlueWoolSlopesQuadriCornerUp.name", "Blue Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevBlueWoolSlopesTriCornerDown.name", "Blue Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevBlueWoolSlopesTriCornerUp.name", "Blue Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevPurpleWoolSlopesQuadriCornerDown.name", "Purple Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevPurpleWoolSlopesQuadriCornerUp.name", "Purple Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevPurpleWoolSlopesTriCornerDown.name", "Purple Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevPurpleWoolSlopesTriCornerUp.name", "Purple Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevCyanWoolSlopesQuadriCornerDown.name", "Cyan Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevCyanWoolSlopesQuadriCornerUp.name", "Cyan Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevCyanWoolSlopesTriCornerDown.name", "Cyan Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevCyanWoolSlopesTriCornerUp.name", "Cyan Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSilverWoolSlopesQuadriCornerDown.name", "Light Gray Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevSilverWoolSlopesQuadriCornerUp.name", "Light Gray Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevSilverWoolSlopesTriCornerDown.name", "Light Gray Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevSilverWoolSlopesTriCornerUp.name", "Light Gray Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGrayWoolSlopesQuadriCornerDown.name", "Gray Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevGrayWoolSlopesQuadriCornerUp.name", "Gray Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevGrayWoolSlopesTriCornerDown.name", "Gray Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevGrayWoolSlopesTriCornerUp.name", "Gray Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevPinkWoolSlopesQuadriCornerDown.name", "Pink Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevPinkWoolSlopesQuadriCornerUp.name", "Pink Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevPinkWoolSlopesTriCornerDown.name", "Pink Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevPinkWoolSlopesTriCornerUp.name", "Pink Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevLimeWoolSlopesQuadriCornerDown.name", "Lime Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevLimeWoolSlopesQuadriCornerUp.name", "Lime Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevLimeWoolSlopesTriCornerDown.name", "Lime Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevLimeWoolSlopesTriCornerUp.name", "Lime Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevYellowWoolSlopesQuadriCornerDown.name", "Yellow Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevYellowWoolSlopesQuadriCornerUp.name", "Yellow Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevYellowWoolSlopesTriCornerDown.name", "Yellow Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevYellowWoolSlopesTriCornerUp.name", "Yellow Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevLightBlueWoolSlopesQuadriCornerDown.name", "Light Blue Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevLightBlueWoolSlopesQuadriCornerUp.name", "Light Blue Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevLightBlueWoolSlopesTriCornerDown.name", "Light Blue Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevLightBlueWoolSlopesTriCornerUp.name", "Light Blue Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevMagentaWoolSlopesQuadriCornerDown.name", "Magenta Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevMagentaWoolSlopesQuadriCornerUp.name", "Magenta Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevMagentaWoolSlopesTriCornerDown.name", "Magenta Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevMagentaWoolSlopesTriCornerUp.name", "Magenta Corner Slope Inv");
        LanguageRegistry.instance().addStringLocalization("KaevOrangeWoolSlopesQuadriCornerDown.name", "Orange Pyramid Corner");
        LanguageRegistry.instance().addStringLocalization("KaevOrangeWoolSlopesQuadriCornerUp.name", "Orange Pyramid Corner Inv");
        LanguageRegistry.instance().addStringLocalization("KaevOrangeWoolSlopesTriCornerDown.name", "Orange Corner Slope");
        LanguageRegistry.instance().addStringLocalization("KaevOrangeWoolSlopesTriCornerUp.name", "Orange Corner Slope Inv");
    }
}
